### ISSUE TITLE
finish() got an unexpected keyword argument 'dirty'

### ISSUE THREAD

**Issue by jubueche** [nengo/nengo-examples#25]
Hi,
i think this is a version issue with progressbar2 being used. I am trying to run the speech sample where you train the model.
This is the error code:

````
TypeError                                 Traceback (most recent call last)
<ipython-input-10-16285c31d209> in <module>
      1 # create a Nengo DL simulator and set the minibatch size
----> 2 with nengo_dl.Simulator(net, minibatch_size=100) as sim:
      3 
      4     # define an optimizer
      5     optimizer = tf.train.RMSPropOptimizer(0.001)

~/anaconda3/envs/speech-examples/lib/python3.6/site-packages/nengo_dl/simulator.py in __init__(self, network, dt, seed, model, dtype, device, unroll_simulation, minibatch_size, tensorboard, progress_bar)
    153                 self.minibatch_size,
    154                 device,
--> 155                 progress,
    156             )
    157 

~/anaconda3/envs/speech-examples/lib/python3.6/site-packages/nengo_dl/tensor_graph.py in __init__(self, model, dt, unroll_simulation, dtype, minibatch_size, device, progress)
    140                 old_operators = operators
    141                 for simp in simplifications:
--> 142                     operators = simp(operators)
    143 
    144         # group mergeable operators

~/anaconda3/envs/speech-examples/lib/python3.6/site-packages/progressbar/bar.py in __exit__(self, exc_type, exc_value, traceback)

TypeError: finish() got an unexpected keyword argument 'dirty'
````

There is smth. wrong with the versions being used in your instructions. Also, you should consider mentioning that you need the nengo 2.8.0 version.

Thanks for your help,
Julian

**Comment by arvoelke** [comment]
Which example are you trying to run?

**Comment by jubueche** [comment]
There is a branch called speech-samples (or smth. like this). The notebook is the loihi one

**Comment by arvoelke** [comment]
The official example for the Loihi keyword spotter is here: https://www.nengo.ai/nengo-loihi/examples/keyword-spotting.html

Does this help? I'm not sure what would have linked you to that unmerged `speech_models` branch. We're currently looking into that and may get back to you here.

For future reference there is also this forum that is ideal for asking questions about examples and getting help with running or creating Nengo models: https://forum.nengo.ai

Thanks for the question!

**Comment by jubueche** [comment]
The official one doesn’t show how to train it. But yes I will have a look, thanks!
